skin
scrayosnet/xenos pull request #64
Opened 2024-03-11 11:45 UTC by HydrofinLoewenherz

2024-03-11 11:51 UTC, HydrofinLoewenherz commented
- [ ] update merge request title and description
- [ ] implement cape endpoint

2024-03-13 22:48 UTC, scrayos requested changes

2024-03-14 12:32 UTC, HydrofinLoewenherz commented on proto/profile.proto
> +    bytes bytes = 3;
Should be OK. How would you call the field? 
- `include_default`
- `send_default`
- `no_default`
- `default_allowed`
- `with_default`

2024-03-14 12:33 UTC, HydrofinLoewenherz commented on proto/profile.proto
>      rpc GetSkin(SkinRequest) returns (SkinResponse);
Should be OK. How would you call the field? 
- `include_default`
- `send_default`
- `no_default`
- `default_allowed`
- `with_default`
- ...

2024-03-14 12:34 UTC, HydrofinLoewenherz commented on proto/profile.proto
> +    bytes bytes = 3;
No reason. But I would like to keep the metadata fields together. So we could do `bytes` always on top.

2024-03-14 18:01 UTC, scrayos commented on proto/profile.proto
>      rpc GetSkin(SkinRequest) returns (SkinResponse);
`include_default` sounds fine.

2024-03-14 18:03 UTC, scrayos commented on proto/profile.proto
> +    bytes bytes = 3;
We can certainly change it the way you did for this time. But in the future, we cannot reallocate/swap index numbers. One of the reasons protobuf includes those indices is that you can visually group keys together while still allowing their internal index to be constant. Therefore, we may preserve that order in the future and just don't mind the assigned indices.

2024-03-15 14:34 UTC, scrayos commented on proto/profile.proto
>      rpc GetSkin(SkinRequest) returns (SkinResponse);
@HydrofinLoewenherz I just realized: We would also need to apply this to getHead, as this would also fall back to the default skin.

2024-03-18 11:49 UTC, scrayos commented on proto/profile.proto
> +    bool include_default = 4;
This should be index 2

2024-03-18 11:49 UTC, scrayos commented on proto/profile.proto
> +    bool include_default = 4;
This should be index 3

2024-03-18 12:43 UTC, scrayos approved these changes

2024-03-18 12:44 UTC, merged